### ISSUE TITLE
Missed files

### ISSUE THREAD

**Issue by sorgelig** [shakalaca/ZenFone-vold#2]
It seems, at least Ntfs.cpp and Exfat.cpp are missed in patch.

**Comment by shakalaca** [comment]
oooops, my fault .. how stupid I am ... :(

**Comment by sorgelig** [comment]
May be you've used CM as a source. It has both files. But AOSP hasn't.

Can you help me with related problem? I have one chinese x86 tablet with x86 Android. I want to modify vold, but can't find compatible source. All sources i've tried prodices vold which doesn't react on SD card insertion. Simply ignores it. But i've found that vold from Zenfone 4/5 Kitkat Android (Stock v6.6.3 ROM) is compatible with my tablet. It's fully working. So, if forget about chinese tablet, do you have an idea what source code could be compatible to build ZF4/5 vold? As i understand, you have experience with these phones. So, may be you know how to build vold compatible with KK ZF4/5 Stock ROM?
Upd: found AOSP ROM for ZF5 on your page. Vold doesn't work on my chinese tablet. Only from ZF4/5 stock ROM is working.

**Comment by shakalaca** [comment]
I got the source from https://github.com/android-ia , you may try on your own. BTW what's the brand of your tablet ? :)

**Comment by sorgelig** [comment]
tablet is CUBE iWork7.
I've solved problem by binary patch of vold. I've got vold from ZF5 and patched that way so it execute external file which is shell script which calls fuse version of exfat and ntfs. So, now it looks like tablet has native exfat and ntfs drivers ;)

**Comment by shakalaca** [comment]
Should be in the lasted commit :)
