### ISSUE TITLE
Can't access to exFAT SD card

### ISSUE THREAD

**Issue by BORETS24** [shakalaca/ZenFone-vold#3]
Hi. When I take vold from your source or compile it yourself and replace sibling vold in system/bin/vold, I get NTFS support, but lose access  write to SD card, when I want modify data on SD card from apps, I click "Show SD card", but SD card not see... There only Internal storage. Have solutions?

**Comment by shakalaca** [comment]
Yes I'm looking into this issue, so far no good news ... :(

**Comment by BORETS24** [comment]
May be we can find solutions together? I tried 2 different non-fuse exFAT drivers : exFAT driver from Samsung and sibling Asus driver ,which give Tuxera (it's texfat.ko module from stock boot.img , I can to load it with my custom kernel, when I disable vermagic check). On both drivers can't get access to write sdcard with custom vold(: I think it's because in Asus file system name not exfat or texfat ,it other! AOSP libraries can't determine filesystem type, because if to try make this in Volume.cpp

   } else if (strcmp(fstype, "**texfat**") == 0) {

```
            if (Exfat::check(devicePath)) {
                errno = EIO;
                /* Badness - abort the mount */
                SLOGE("%s failed FS checks (%s)", devicePath, strerror(errno));
                setState(Volume::State_Idle);
                free(fstype);
                return -1;
            }

            if (Exfat::doMount(devicePath, getMountpoint(), false, false, false,
                    AID_MEDIA_RW, AID_MEDIA_RW, 0007, true)) {
                SLOGE("%s failed to mount via EXFAT (%s)\n", devicePath, strerror(errno));
                continue;
               }          
            } else {
```

   or

   } else if (strcmp(fstype, "**exfat**") == 0) {

```
            if (Exfat::check(devicePath)) {
                errno = EIO;
                /* Badness - abort the mount */
                SLOGE("%s failed FS checks (%s)", devicePath, strerror(errno));
                setState(Volume::State_Idle);
                free(fstype);
                return -1;
            }

            if (Exfat::doMount(devicePath, getMountpoint(), false, false, false,
                    AID_MEDIA_RW, AID_MEDIA_RW, 0007, true)) {
                SLOGE("%s failed to mount via EXFAT (%s)\n", devicePath, strerror(errno));
                continue;
               }          
            } else {
```

phone write that Prepare external memory but can't to mount this.

If not determine fstype

} else {

```
            if (Exfat::check(devicePath)) {
                errno = EIO;
                /* Badness - abort the mount */
                SLOGE("%s failed FS checks (%s)", devicePath, strerror(errno));
                setState(Volume::State_Idle);
                free(fstype);
                return -1;
            }

            if (Exfat::doMount(devicePath, getMountpoint(), false, false, false,
                    AID_MEDIA_RW, AID_MEDIA_RW, 0007, true)) {
                SLOGE("%s failed to mount via EXFAT (%s)\n", devicePath, strerror(errno));
                continue;
               }          
            } else {
```

phone mount exfat succesfully

i added to AOSP source blkid exfat- it's not help.

**Comment by shakalaca** [comment]
I got the similar result with your findings, and after digging a little deeper I found out libext2_blkid did not support exfat and couldn't get the right metadata from SD card.

After applying the commit from here: http://review.cyanogenmod.org/#/c/113319/ I can mount and use the SD card successfully. But the strange thing is ASUS do not have this patch so how the hell did they read the metadata ?

**Comment by shakalaca** [comment]
BTW the key information we're missing is "UUID of SD card", I tried returning dummy UUID and everything worked. :)

**Comment by BORETS24** [comment]
Yes, I tried blkid patch-not take effect with it or not SD card not mounting if determine fstype exfat, without determine fstype - mounted, but haven't write access to SD card. I think Asus vold take fstype from texfat.ko module because only with it you get write access. If use exFAT Samsung driver you can't write access even with stock Asus vold. May you explain what is UUID dummy?

**Comment by shakalaca** [comment]
Upload my new patch, please have a look :)

When your app asking for SD card location, the DocumentsUI shows up and lists the storage supported on the device. It uses UUID to identify each storage and from logcat I notice it can get UUID for SD card with exFAT format when using stock vold but failed when using my build. So I change the last lines of Volume.cpp (https://android.googlesource.com/platform/system/vold/+/android-5.0.2_r3/Volume.cpp#693) to setUuid("1234-5678"); and DocumentsUI finally found my SD card. Either the blkid is broken or the stock vold has its way getting metadata of SD card.

**Comment by BORETS24** [comment]
Thanks for finded solution! Working!!! But find trouble, when i set UUiD to  "1234-5678": apps installed on SD card now corrupted, phone write that app not installed. When install stock vold- apps on sdcard see again :)

P.S. Now I tried your new vold binary- exFAT sdcard not mounted for me.

P.P.S. I understand, for work new vold need to replace libext2_blkid.so.
